# Generated by Django 2.0.9 on 2018-10-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo inicial')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='slideshow/imagens', verbose_name='Imagem')),
            ],
        ),
    ]
