# Generated by Django 2.0.9 on 2018-10-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quem_somos_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='quem_somos',
            name='video_id',
            field=models.CharField(default='', max_length=32),
        ),
    ]
